(define (equal? a b)
    (cond ((and (pair? a) (pair? b)) 
            (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b))))
        ((eq? a b) true)
        (else false)))

(newline)
(display (equal? '(this is a list) '(this is a list)))
(newline)
(display (equal? '(this is a list) '(this (is a) list)))