(define (cubeRt x)
  (define (improve guess x)
    (/ (+ (/ x (* y y)) (* 2 y)) 3))
  (define (cube x)
    (* x x x))
  (define (good-enough? guess x)
    (< (abs (/ (- x (cube guess)) x) ) 0.001))
  (if (good-enough? guess x)
      guess
      (cubrt-iter (improve guess x)))
